In [6]:
from xml.etree.ElementTree import ElementTree as ET

# My modules
from mongo_connect import Connection
# from internal_data.levels import levels
# from bod_api import Object, Document, Record
from settings import BODSettings

settings = BODSettings().load().validate()

bod = Connection('BoD')
bod_v2 = Connection('BoD_v2')
bod_desc = Connection(settings.actual_db_desc)
dgrad = settings.dgrad
current_version = settings.current_version

In [1]:
from geojson import LineString, Point, Polygon

In [2]:
line = LineString((Point((1,2)), Point((3,4))))

In [10]:
poly = Polygon((Point((1,2)), Point((3,4))))

In [11]:
poly

{"coordinates": [[1, 2], [3, 4]], "type": "Polygon"}

In [1]:
from bod_api import BODClient

In [2]:
bod_client = BODClient()

In [3]:
set([item['LEVEL'] for item in bod_client.get_db('BoD').get_coll('addrobj').find({}, limit=10000)])

{'1', '14', '15', '16', '2', '3', '4', '5', '6', '7', '8'}

In [5]:
for collection_name in ['addrobj', 'steads', 'houses', 'apartments', 'rooms', 'carplaces']:
    item = bod_client.get_db('BoD').get_coll(collection_name).find_one()
    print(item.keys())

dict_keys(['_id', 'ID', 'OBJECTID', 'OBJECTGUID', 'CHANGEID', 'NAME', 'TYPENAME', 'LEVEL', 'OPERTYPEID', 'PREVID', 'NEXTID', 'UPDATEDATE', 'STARTDATE', 'ENDDATE', 'ISACTUAL', 'ISACTIVE'])
dict_keys(['_id', 'ID', 'OBJECTID', 'OBJECTGUID', 'CHANGEID', 'NUMBER', 'OPERTYPEID', 'PREVID', 'NEXTID', 'UPDATEDATE', 'STARTDATE', 'ENDDATE', 'ISACTUAL', 'ISACTIVE'])
dict_keys(['_id', 'ID', 'OBJECTID', 'OBJECTGUID', 'CHANGEID', 'HOUSENUM', 'HOUSETYPE', 'OPERTYPEID', 'PREVID', 'NEXTID', 'UPDATEDATE', 'STARTDATE', 'ENDDATE', 'ISACTUAL', 'ISACTIVE'])
dict_keys(['_id', 'ID', 'OBJECTID', 'OBJECTGUID', 'CHANGEID', 'NUMBER', 'APARTTYPE', 'OPERTYPEID', 'PREVID', 'NEXTID', 'UPDATEDATE', 'STARTDATE', 'ENDDATE', 'ISACTUAL', 'ISACTIVE'])
dict_keys(['_id', 'ID', 'OBJECTID', 'OBJECTGUID', 'CHANGEID', 'NUMBER', 'ROOMTYPE', 'OPERTYPEID', 'PREVID', 'NEXTID', 'UPDATEDATE', 'STARTDATE', 'ENDDATE', 'ISACTUAL', 'ISACTIVE'])
dict_keys(['_id', 'ID', 'OBJECTID', 'OBJECTGUID', 'CHANGEID', 'NUMBER', 'OPERTYPEID', 'PREVID', 'NEXTID', 'UPDATEDATE', 'STARTDATE', 'ENDDATE', 'ISACTUAL', 'ISACTIVE'])

In [7]:
print(*(bod_client.get_db('BoD').get_coll('addrobj').find({ '$text': { '$search': "гимовское" } })), sep='\n')

{'_id': ObjectId('629fce25fdc3a4e7a495552a'), 'ID': '1646484', 'OBJECTID': '1333503', 'OBJECTGUID': 'c6d032d0-a97f-4550-8240-c4c4efd805d8', 'CHANGEID': '3649756', 'NAME': 'Лесная', 'TYPENAME': 'ул', 'LEVEL': '8', 'OPERTYPEID': '1', 'PREVID': '0', 'NEXTID': '1851420', 'UPDATEDATE': '2020-07-03', 'STARTDATE': '1900-01-01', 'ENDDATE': '2020-07-03', 'ISACTUAL': '0', 'ISACTIVE': '0'}
{'_id': ObjectId('629fce25fdc3a4e7a495552b'), 'ID': '1851420', 'OBJECTID': '1333503', 'OBJECTGUID': 'c6d032d0-a97f-4550-8240-c4c4efd805d8', 'CHANGEID': '152749848', 'NAME': 'Лесная', 'TYPENAME': 'ул', 'LEVEL': '8', 'OPERTYPEID': '30', 'PREVID': '1646484', 'UPDATEDATE': '2020-07-03', 'STARTDATE': '2020-07-03', 'ENDDATE': '2079-06-06', 'ISACTUAL': '1', 'ISACTIVE': '0'}

In [3]:
mun = bod_client.get_db('BoD').get_coll('munhierarchy')

In [20]:
adm = bod_client.get_db('BoD').get_coll('admhierarchy')

In [5]:
mun.find_one({'OBJECTID': '1325470'})

{'_id': ObjectId('629fd461fdc3a4e7a41e4445'),
 'ID': '39855941',
 'OBJECTID': '1325470',
 'PARENTOBJID': '95250260',
 'CHANGEID': '3630427',
 'OKTMO': '73705000001',
 'PREVID': '0',
 'NEXTID': '0',
 'UPDATEDATE': '2021-03-29',
 'STARTDATE': '1900-01-01',
 'ENDDATE': '2079-06-06',
 'ISACTIVE': '1',
 'PATH': '1325381.95250260.1325470'}

In [22]:
adm.find_one({'OBJECTID': '1325470'})

{'_id': ObjectId('629fcf2dfdc3a4e7a4988306'),
 'ID': '71227140',
 'OBJECTID': '1325470',
 'PARENTOBJID': '1325381',
 'CHANGEID': '3630427',
 'REGIONCODE': '73',
 'AREACODE': '0',
 'CITYCODE': '2',
 'PLACECODE': '0',
 'PLANCODE': '0',
 'STREETCODE': '0',
 'PREVID': '0',
 'NEXTID': '0',
 'UPDATEDATE': '1900-01-01',
 'STARTDATE': '1900-01-01',
 'ENDDATE': '2079-06-06',
 'ISACTIVE': '1',
 'PATH': '1325381.1325470'}

In [146]:
city_id = '1325470'
print(*(adm.find({'PATH': {'$regex': city_id+r'\.\d+$'}}, limit=10)), sep='\n')

{'_id': ObjectId('629fcf2dfdc3a4e7a4988307'), 'ID': '71227167', 'OBJECTID': '1326580', 'PARENTOBJID': '1325470', 'CHANGEID': '3633142', 'REGIONCODE': '73', 'AREACODE': '0', 'CITYCODE': '2', 'PLACECODE': '0', 'PLANCODE': '0', 'STREETCODE': '63', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '1900-01-01', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.1325470.1326580'}
{'_id': ObjectId('629fcf2dfdc3a4e7a4988a5c'), 'ID': '71248189', 'OBJECTID': '1326272', 'PARENTOBJID': '1325470', 'CHANGEID': '3632437', 'REGIONCODE': '73', 'AREACODE': '0', 'CITYCODE': '2', 'PLACECODE': '0', 'PLANCODE': '0', 'STREETCODE': '3', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '1900-01-01', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.1325470.1326272'}
{'_id': ObjectId('629fcf2dfdc3a4e7a4988b67'), 'ID': '71252133', 'OBJECTID': '1326652', 'PARENTOBJID': '1325470', 'CHANGEID': '3633322', 'REGIONCODE': '73', 'AREACODE': '0', 'CITYCODE': '2', 'PLACECODE': '0', 'PLANCODE': '0', 'STREETCODE': '111', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '1900-01-01', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.1325470.1326652'}
{'_id': ObjectId('629fcf2dfdc3a4e7a4988b72'), 'ID': '71252238', 'OBJECTID': '1326858', 'PARENTOBJID': '1325470', 'CHANGEID': '3633766', 'REGIONCODE': '73', 'AREACODE': '0', 'CITYCODE': '2', 'PLACECODE': '0', 'PLANCODE': '0', 'STREETCODE': '130', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '1900-01-01', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.1325470.1326858'}
{'_id': ObjectId('629fcf2dfdc3a4e7a4988b79'), 'ID': '71252305', 'OBJECTID': '1326879', 'PARENTOBJID': '1325470', 'CHANGEID': '3633842', 'REGIONCODE': '73', 'AREACODE': '0', 'CITYCODE': '2', 'PLACECODE': '0', 'PLANCODE': '0', 'STREETCODE': '138', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '1900-01-01', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.1325470.1326879'}
{'_id': ObjectId('629fcf2dfdc3a4e7a4988bcf'), 'ID': '71253326', 'OBJECTID': '1326930', 'PARENTOBJID': '1325470', 'CHANGEID': '3633967', 'REGIONCODE': '73', 'AREACODE': '0', 'CITYCODE': '2', 'PLACECODE': '0', 'PLANCODE': '0', 'STREETCODE': '116', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '1900-01-01', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.1325470.1326930'}
{'_id': ObjectId('629fcf2dfdc3a4e7a4988bf0'), 'ID': '71253633', 'OBJECTID': '1326906', 'PARENTOBJID': '1325470', 'CHANGEID': '3633913', 'REGIONCODE': '73', 'AREACODE': '0', 'CITYCODE': '2', 'PLACECODE': '1', 'PLANCODE': '0', 'STREETCODE': '0', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '1900-01-01', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.1325470.1326906'}
{'_id': ObjectId('629fcf2dfdc3a4e7a4988bf1'), 'ID': '71253654', 'OBJECTID': '1326755', 'PARENTOBJID': '1325470', 'CHANGEID': '3633545', 'REGIONCODE': '73', 'AREACODE': '0', 'CITYCODE': '2', 'PLACECODE': '0', 'PLANCODE': '0', 'STREETCODE': '107', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '1900-01-01', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.1325470.1326755'}
{'_id': ObjectId('629fcf2efdc3a4e7a49890fd'), 'ID': '71267824', 'OBJECTID': '1326908', 'PARENTOBJID': '1325470', 'CHANGEID': '3633916', 'REGIONCODE': '73', 'AREACODE': '0', 'CITYCODE': '2', 'PLACECODE': '0', 'PLANCODE': '0', 'STREETCODE': '153', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '1900-01-01', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.1325470.1326908'}
{'_id': ObjectId('629fcf2efdc3a4e7a498910d'), 'ID': '71268041', 'OBJECTID': '1326827', 'PARENTOBJID': '1325470', 'CHANGEID': '3633695', 'REGIONCODE': '73', 'AREACODE': '0', 'CITYCODE': '2', 'PLACECODE': '0', 'PLANCODE': '0', 'STREETCODE': '196', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '1900-01-01', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.1325470.1326827'}

In [152]:
import pandas as pd

In [156]:
streets_ids = set(pd.DataFrame(bod_client.get_db('BoD').get_coll('reestrobjects').find({'LEVELID': '8', 'ISACTIVE': '1'}))['OBJECTID'])

In [159]:
streets_ids & {'1337020'}

{'1337020'}

In [161]:
'1337020' + r'\.\d+$'

'1337020\\.\\d+$'

In [155]:
print(*(mun.find({'PATH': {'$regex': r'1325470.\d+$'}, 'ISACTIVE': '1'}, limit=10)), sep='\n')

{'_id': ObjectId('629fd413fdc3a4e7a4155950'), 'ID': '40257608', 'OBJECTID': '1329563', 'PARENTOBJID': '1325470', 'CHANGEID': '3640195', 'OKTMO': '73705000001', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '2016-09-28', 'STARTDATE': '2016-09-28', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.95250260.1325470.1329563'}
{'_id': ObjectId('629fd414fdc3a4e7a4155fbb'), 'ID': '40205142', 'OBJECTID': '1330344', 'PARENTOBJID': '1325470', 'CHANGEID': '3641980', 'OKTMO': '73705000001', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '2020-12-21', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.95250260.1325470.1330344'}
{'_id': ObjectId('629fd414fdc3a4e7a4155fc8'), 'ID': '40366396', 'OBJECTID': '1331118', 'PARENTOBJID': '1325470', 'CHANGEID': '3643935', 'OKTMO': '73705000001', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '2020-12-22', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.95250260.1325470.1331118'}
{'_id': ObjectId('629fd414fdc3a4e7a41566e3'), 'ID': '40829799', 'OBJECTID': '1335046', 'PARENTOBJID': '1325470', 'CHANGEID': '3653543', 'OKTMO': '73705000001', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '2020-12-16', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.95250260.1325470.1335046'}
{'_id': ObjectId('629fd414fdc3a4e7a41567bf'), 'ID': '40774598', 'OBJECTID': '1334072', 'PARENTOBJID': '1325470', 'CHANGEID': '3651446', 'OKTMO': '73705000001', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '2016-09-28', 'STARTDATE': '2016-09-28', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.95250260.1325470.1334072'}
{'_id': ObjectId('629fd414fdc3a4e7a4156a2d'), 'ID': '40366226', 'OBJECTID': '1331116', 'PARENTOBJID': '1325470', 'CHANGEID': '3643984', 'OKTMO': '73705000001', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '2021-03-29', 'STARTDATE': '2016-09-29', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.95250260.1325470.1331116'}
{'_id': ObjectId('629fd414fdc3a4e7a4156dc3'), 'ID': '40206380', 'OBJECTID': '1330426', 'PARENTOBJID': '1325470', 'CHANGEID': '3642240', 'OKTMO': '73705000001', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '2020-12-21', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.95250260.1325470.1330426'}
{'_id': ObjectId('629fd414fdc3a4e7a4156e4d'), 'ID': '40111448', 'OBJECTID': '1328418', 'PARENTOBJID': '1325470', 'CHANGEID': '3637465', 'OKTMO': '73705000001', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '2016-09-28', 'STARTDATE': '2016-09-28', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.95250260.1325470.1328418'}
{'_id': ObjectId('629fd414fdc3a4e7a4156e78'), 'ID': '40499259', 'OBJECTID': '1331685', 'PARENTOBJID': '1325470', 'CHANGEID': '3645435', 'OKTMO': '73705000001', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '2019-09-06', 'STARTDATE': '2019-09-06', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.95250260.1325470.1331685'}
{'_id': ObjectId('629fd414fdc3a4e7a41574cc'), 'ID': '40236443', 'OBJECTID': '1329949', 'PARENTOBJID': '1325470', 'CHANGEID': '3641083', 'OKTMO': '73705000001', 'PREVID': '0', 'NEXTID': '0', 'UPDATEDATE': '2020-12-22', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'ISACTIVE': '1', 'PATH': '1325381.95250260.1325470.1329949'}

In [75]:
bod_client.get_db('BoD').get_coll('addrobjdivision').find_one({'PARENTID': '1325470'})

In [25]:
print(*(bod_client.get_db('BoD').get_coll('objectlevels').find({})), sep='\n')

{'_id': ObjectId('629fda3efdc3a4e7a448dd91'), 'LEVEL': '1', 'NAME': 'Субъект РФ', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dd92'), 'LEVEL': '2', 'NAME': 'Административный район', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dd93'), 'LEVEL': '3', 'NAME': 'Муниципальный район', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dd94'), 'LEVEL': '4', 'NAME': 'Сельское/городское поселение', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dd95'), 'LEVEL': '5', 'NAME': 'Город', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dd96'), 'LEVEL': '6', 'NAME': 'Населенный пункт', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dd97'), 'LEVEL': '7', 'NAME': 'Элемент планировочной структуры', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dd98'), 'LEVEL': '8', 'NAME': 'Элемент улично-дорожной сети', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dd99'), 'LEVEL': '9', 'NAME': 'Земельный участок', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dd9a'), 'LEVEL': '10', 'NAME': 'Здание (сооружение)', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dd9b'), 'LEVEL': '11', 'NAME': 'Помещение', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dd9c'), 'LEVEL': '12', 'NAME': 'Помещения в пределах помещения', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dd9d'), 'LEVEL': '13', 'NAME': 'Уровень автономного округа (устаревшее)', 'STARTDATE': '1900-01-01', 'ENDDATE': '2015-11-01', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dd9e'), 'LEVEL': '14', 'NAME': 'Уровень внутригородской территории (устаревшее)', 'STARTDATE': '1900-01-01', 'ENDDATE': '2015-11-01', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dd9f'), 'LEVEL': '15', 'NAME': 'Уровень дополнительных территорий (устаревшее)', 'STARTDATE': '1900-01-01', 'ENDDATE': '2015-11-01', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dda0'), 'LEVEL': '16', 'NAME': 'Уровень объектов на дополнительных территориях (устаревшее)', 'STARTDATE': '1900-01-01', 'ENDDATE': '2015-11-01', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}
{'_id': ObjectId('629fda3efdc3a4e7a448dda1'), 'LEVEL': '17', 'NAME': 'Машино-место', 'STARTDATE': '1900-01-01', 'ENDDATE': '2079-06-06', 'UPDATEDATE': '1900-01-01', 'ISACTIVE': 'true'}

In [76]:
bod = bod_client.get_db('BoD')

In [142]:
for item in bod.get_coll('admhierarchy').find_one({}, skip=40)['PATH'].split('.'):
    obj = bod.get_coll('addrobj').find_one({'OBJECTID': item})
    if obj is not None:
        print(obj['NAME'], obj['TYPENAME'])
    else:
        obj = bod.get_coll('houses').find_one({'OBJECTID': item})
        if obj is not None:
            print(obj['HOUSENUM'])

Ульяновская обл
Ульяновск г
Московское ш
40А

In [16]:
import math


class GeoObject:
    def __init__(self, type: str, coordinates: object):
        self.type = type
        self.coordinates = coordinates

    def to_dict(self) -> dict:
        return {
            "type": self.type,
            "coordinates": self.coordinates
        }

    def calc(self) -> float:
        """
        Returns the area (for polygons) or length (for lines) of the geo object.
        """
        if self.type == "line":
            length = 0
            for i in range(len(self.coordinates) - 1):
                p1 = self.coordinates[i]
                p2 = self.coordinates[i+1]
                length += math.sqrt((p1[0]-p2[0])**2 + (p1[1]-p2[1])**2)
                return round(length,3)

In [17]:
test = GeoObject('line', ([1, 2], [3, 4]))

In [18]:
test.area_length()

2.828

In [20]:
test.__dict__

{'type': 'line', 'coordinates': ([1, 2], [3, 4])}

In [6]:
import pandas as pd
from bod_api import BODClient
client = BODClient()
db = client.get_db('BoD')
rec = db.get_coll('addrobj').get_records(limit=1000)

In [1]:
from bod_schema import BODSchema
schema = BODSchema()

In [4]:
schema.find_coll('addrobj').fields

[FieldSchema(name='ID', string='Уникальный идентификатор записи. Ключевое поле', type=<class 'int'>, required=True),
 FieldSchema(name='OBJECTID', string='Глобальный уникальный идентификатор адресного объекта типа INTEGER', type=<class 'int'>, required=True),
 FieldSchema(name='OBJECTGUID', string='Глобальный уникальный идентификатор адресного объекта типа UUID', type=<class 'str'>, required=True),
 FieldSchema(name='CHANGEID', string='ID изменившей транзакции', type=<class 'int'>, required=True),
 FieldSchema(name='NAME', string='Наименование', type=<class 'str'>, required=True),
 FieldSchema(name='TYPENAME', string='Краткое наименование типа объекта', type=<class 'str'>, required=True),
 FieldSchema(name='LEVEL', string='Уровень адресного объекта', type=<class 'str'>, required=True),
 FieldSchema(name='OPERTYPEID', string='Статус действия над записью – причина появления записи', type=<class 'int'>, required=True),
 FieldSchema(name='PREVID', string='Идентификатор записи связывания с предыдущей исторической записью', type=<class 'int'>, required=False),
 FieldSchema(name='NEXTID', string='Идентификатор записи связывания с последующей исторической записью', type=<class 'int'>, required=False),
 FieldSchema(name='UPDATEDATE', string='Дата внесения (обновления) записи', type=<class 'datetime.datetime'>, required=True),
 FieldSchema(name='STARTDATE', string='Начало действия записи', type=<class 'datetime.datetime'>, required=True),
 FieldSchema(name='ENDDATE', string='Окончание действия записи', type=<class 'datetime.datetime'>, required=True),
 FieldSchema(name='ISACTUAL', string='Статус актуальности адресного объекта ФИАС', type=<class 'int'>, required=True),
 FieldSchema(name='ISACTIVE', string='Признак действующего адресного объекта', type=<class 'int'>, required=True)]

In [5]:
coll_schema = schema.find_coll('addrobj')

In [4]:
client = client.reload_client()

In [5]:
client.get_database('BoD').get_collection('addrobj').find_one({})

{'_id': ObjectId('629fce25fdc3a4e7a4955518'),
 'ID': '1822147',
 'OBJECTID': '95250250',
 'OBJECTGUID': '3ef2701b-c647-4643-9421-5c127dfeb3a3',
 'CHANGEID': '138206767',
 'NAME': 'Гимовское',
 'TYPENAME': 'с.п.',
 'LEVEL': '4',
 'OPERTYPEID': '0',
 'PREVID': '0',
 'NEXTID': '0',
 'UPDATEDATE': '2011-01-01',
 'STARTDATE': '2011-01-01',
 'ENDDATE': '2079-06-06',
 'ISACTUAL': '1',
 'ISACTIVE': '1'}

In [4]:
BODClient.get_dataframe('73\AS_HOUSE_TYPES_20211125_1b2c8bbd-dd0d-45d6-9685-27ab2d6f83cf.XML').query('ISACTIVE == "true"')

,ID,NAME,SHORTNAME,DESC,ISACTIVE,UPDATEDATE,STARTDATE,ENDDATE
1,2,Дом,д.,Дом,true,1900-01-01,1900-01-01,2079-06-06
3,4,Гараж,г-ж,Гараж,true,1900-01-01,1900-01-01,2079-06-06
4,5,Здание,зд.,Здание,true,1900-01-01,1900-01-01,2079-06-06
5,6,Шахта,шахта,Шахта,true,1900-01-01,1900-01-01,2079-06-06
6,7,Строение,стр.,Строение,true,1900-01-01,1900-01-01,2079-06-06
7,8,Сооружение,соор.,Сооружение,true,1900-01-01,1900-01-01,2079-06-06
9,10,Корпус,к.,Корпус,true,1900-01-01,1900-01-01,2079-06-06

In [29]:
df = pd.DataFrame(bod.get_coll('munhierarchy').find({}))

In [37]:
df.sample(5)

,_id,ID,OBJECTID,PARENTOBJID,CHANGEID,OKTMO,PREVID,NEXTID,UPDATEDATE,STARTDATE,ENDDATE,ISACTIVE,PATH
385772,629fd447fdc3a4e7a41b2cb1,45309558,4583409,1332531,8565939,73701000,0,0,1900-01-01,1900-01-01,2079-06-06,0,1325381.95250397.1325680.1332531.4583409
301847,629fd43cfdc3a4e7a419e3c1,46850508,32987124,32983687,50320543,73701000,0,0,2018-11-21,2018-11-21,2079-06-06,1,1325381.95250397.1325680.1337960.32983687.3298...
588122,629fd462fdc3a4e7a41e45d3,97618787,34707647,1344703,52818094,73625465101,0,0,2019-10-02,2019-10-02,2079-06-06,1,1325381.95250293.95250301.1336024.1344703.3470...
93572,629fd41ffdc3a4e7a416b39a,44294226,20902678,20898717,32685662,73701000,0,0,2017-07-04,2017-07-04,2079-06-06,1,1325381.95250397.1325680.1329526.20898717.2090...
445858,629fd44ffdc3a4e7a41c181e,40907926,5232074,1335440,9536598,73705000001,0,0,2019-09-05,2019-09-05,2079-06-06,1,1325381.95250260.1325470.1335440.5232074

In [2]:
def get_df(path):
    et = ET.parse(path)
    root = et.getroot()
    df = pd.DataFrame.from_dict(data=[x.attrib for x in root if x.attrib != {}])
    return df

In [3]:
df = get_df('73\AS_MUN_HIERARCHY_20211125_4a319d27-b45a-48f5-86a3-b691f77db25b.XML')

In [84]:
df[:5]

,_id,ID,OBJECTID,PARENTOBJID,CHANGEID,OKTMO,PREVID,NEXTID,UPDATEDATE,STARTDATE,ENDDATE,ISACTIVE,PATH
0,629fd413fdc3a4e7a41544ea,43601783,52892432,52885177,79210799,73701000,0,0,2018-08-07,2018-08-07,2079-06-06,1,1325381.95250397.1325680.1328735.52885177.5289...
1,629fd413fdc3a4e7a41544eb,43611123,53018674,53000815,79391126,73701000,0,0,2018-08-07,2018-08-07,2079-06-06,1,1325381.95250397.1325680.1328735.53000815.5301...
2,629fd413fdc3a4e7a41544ec,43616362,53085967,53067851,79487000,73701000,0,0,2018-08-07,2018-08-07,2079-06-06,1,1325381.95250397.1325680.1328735.53067851.5308...
3,629fd413fdc3a4e7a41544ed,43618003,53095285,53089915,79499415,73701000,0,0,2018-08-07,2018-08-07,2079-06-06,1,1325381.95250397.1325680.1328735.53089915.5309...
4,629fd413fdc3a4e7a41544ee,43623438,53139515,53132437,79558494,73701000,0,0,2018-08-07,2018-08-07,2079-06-06,1,1325381.95250397.1325680.1328735.53132437.5313...

In [88]:
df[(df['ENDDATE'] == '2079-06-06') & (df['ISACTIVE'] == '0')]

,ID,OBJECTID,PARENTOBJID,CHANGEID,OKTMO,PREVID,NEXTID,UPDATEDATE,STARTDATE,ENDDATE,ISACTIVE,PATH
80,44792289,63384096,1331392,94596943,73701000,0,0,2020-05-21,1900-01-01,2079-06-06,0,1325381.95250397.1325680.1331392.63384096
81,44817182,63465857,1331392,94713047,73701000,0,0,2020-05-21,1900-01-01,2079-06-06,0,1325381.95250397.1325680.1331392.63465857
98,44957010,4486183,1332281,8424332,73701000,0,0,1900-01-01,1900-01-01,2079-06-06,0,1325381.95250397.1325680.1332281.4486183
160,45445000,10163147,1332939,16742115,73701000,0,0,1900-01-01,1900-01-01,2079-06-06,0,1325381.95250397.1325680.1332939.10163147
382,47238206,3902443,1338479,7599186,73701000,0,0,2020-02-21,1900-01-01,2079-06-06,0,1325381.95250397.1325680.1338479.3902443
...,...,...,...,...,...,...,...,...,...,...,...,...
920011,47363107,32315145,32300281,49331151,73701000,0,0,2021-11-23,2018-08-16,2079-06-06,0,1325381.95250397.1325680.1339070.32300281.3231...
920012,47365122,32391666,32300281,49441705,73701000,0,0,2021-11-23,2018-08-16,2079-06-06,0,1325381.95250397.1325680.1339070.32300281.3239...
920020,44580371,69693036,1330873,103867948,73701000,0,0,1900-01-01,1900-01-01,2079-06-06,0,1325381.95250397.1325680.1330873.69693036
920021,44580806,69705193,1330873,103884952,73701000,0,0,1900-01-01,1900-01-01,2079-06-06,0,1325381.95250397.1325680.1330873.69705193
920026,46163254,45197312,1336020,68093510,73701000001,0,0,2021-07-08,1900-01-01,2079-06-06,0,1325381.95250397.1325680.1336020.45197312

In [68]:
df[['OBJECTID', 'PARENTOBJID']].groupby(by='OBJECTID')['PARENTOBJID'].apply(list).to_dict()

{'10000005': ['9997447'],
 '100000318': ['45055612'],
 '100000319': ['45055612'],
 '10000038': ['9997447'],
 '10000046': ['1339546'],
 '10000126': ['9997447'],
 '10000298': ['9997447'],
 '10000303': ['1338804'],
 '10000357': ['9997447'],
 '10000397': ['9997447'],
 '100005306': ['1341000'],
 '10000641': ['1340161'],
 '10000810': ['9997447'],
 '10000837': ['9997447'],
 '100008374': ['1327594'],
 '10000849': ['9997447'],
 '10000859': ['9997447'],
 '10000867': ['9997447'],
 '10000874': ['9997447'],
 '10000886': ['9997447'],
 '10000904': ['9997447'],
 '10000912': ['1340161'],
 '100009187': ['1338099'],
 '10000967': ['1340515'],
 '100009982': ['1337052'],
 '10001003': ['1338804'],
 '100010392': ['1337644'],
 '100010428': ['1337644'],
 '100010587': ['1343060'],
 '100010612': ['1348615'],
 '100010894': ['1343832'],
 '10001146': ['1339546'],
 '10001163': ['9997447'],
 '100012748': ['1344442'],
 '100013667': ['1333588'],
 '100013689': ['1330415'],
 '100013720': ['1333119'],
 '100013727': ['1333119'],
 '100013759': ['1339715'],
 '100013805': ['1334607'],
 '100014075': ['5969942'],
 '10001430': ['1340515'],
 '10001455': ['9997447'],
 '100014726': ['1325680'],
 '100014728': ['1325680'],
 '100015390': ['1337137'],
 '10001608': ['9997447'],
 '10001638': ['9997447'],
 '100016469': ['1329639'],
 '10001649': ['9997447'],
 '100016507': ['1339070'],
 '10001770': ['9997447'],
 '10001791': ['9997447'],
 '10002030': ['1338804'],
 '10002039': ['9997447'],
 '10002101': ['1339546'],
 '10002212': ['9997447'],
 '10002229': ['9997447'],
 '10002242': ['9997447'],
 '10002349': ['1340161'],
 '100024445': ['1342452'],
 '100024575': ['1337512'],
 '100025449': ['1335191'],
 '10002614': ['9997447'],
 '10002621': ['9997447'],
 '10002626': ['9997447'],
 '10002631': ['9997447'],
 '100026783': ['1339257'],
 '10002694': ['9997447'],
 '10002702': ['9997447'],
 '10002709': ['1340161'],
 '10002733': ['1338804'],
 '100027374': ['1339257'],
 '100027391': ['1346862'],
 '10002823': ['9997447'],
 '10002949': ['9997447'],
 '10002950': ['9997447'],
 '10002952': ['9997447'],
 '10002953': ['9997447'],
 '10002954': ['9997447'],
 '10002955': ['9997447'],
 '10002956': ['9997447'],
 '10003004': ['9997447'],
 '10003011': ['9997447'],
 '10003017': ['9997447'],
 '10003024': ['9997447'],
 '10003034': ['9997447'],
 '10003038': ['9997447'],
 '10003044': ['9997447'],
 '10003057': ['9997447'],
 '10003065': ['9997447'],
 '10003074': ['9997447'],
 '10003081': ['9997447'],
 '10003087': ['9997447'],
 '10003183': ['1340161'],
 '10003256': ['9997447'],
 '100032965': ['1337565'],
 '100032970': ['1334478'],
 '100033029': ['1339305'],
 '100033046': ['1339681'],
 '100033085': ['1341981'],
 '100033129': ['1330064'],
 '100033150': ['1333928'],
 '100033160': ['1334926'],
 '100033161': ['1334926'],
 '100033190': ['1329180'],
 '10003366': ['9997447'],
 '10003383': ['9997447'],
 '10003395': ['9997447'],
 '10003405': ['9997447'],
 '10003419': ['9997447'],
 '10003435': ['9997447'],
 '100034636': ['1334402'],
 '100034679': ['1334402'],
 '100035652': ['1330712'],
 '100035653': ['1330712'],
 '100035654': ['1330712'],
 '100035655': ['1330712'],
 '100035656': ['1330712'],
 '100035657': ['1330712'],
 '100035658': ['1330712'],
 '100035659': ['1330712'],
 '100035660': ['1330712'],
 '100035661': ['1330712'],
 '100035662': ['1330712'],
 '100035663': ['1330712'],
 '10003766': ['9997447'],
 '10003799': ['1340161'],
 '10003843': ['1339546'],
 '10003855': ['1338804'],
 '10003997': ['9997447'],
 '10004059': ['10001430'],
 '10004065': ['10001430'],
 '100041179': ['1345825'],
 '100041186': ['1345825'],
 '10004155': ['1340161'],
 '100041593': ['1342658'],
 '100041600': ['1342658'],
 '10004176': ['9997447'],
 '10004225': ['9997447'],
 '10004235': ['9997447'],
 '10004240': ['9997447'],
 '10004248': ['9997447'],
 '10004255': ['9997447'],
 '10004264': ['9997447'],
 '10004276': ['9997447'],
 '10004285': ['9997447'],
 '10004289': ['9997447'],
 '10004293': ['9997447'],
 '10004298': ['9997447'],
 '10004306': ['9997447'],
 '10004314': ['9997447'],
 '10004323': ['9997447'],
 '10004332': ['9997447'],
 '10004548': ['1338804'],
 '10004681': ['9997447'],
 '100046871': ['1333119'],
 '10004696': ['1339546'],
 '100047275': ['1343461'],
 '100047308': ['1346628'],
 '100047310': ['1343461'],
 '100047312': ['1343461'],
 '100047313': ['1343461'],
 '100047338': ['1343461'],
 '100047371': ['1342693'],
 '100047372': ['1335362'],
 '100047373': ['1340170'],
 '100048239': ['1342693'],
 '100048251': ['1335362'],
 '10004837': ['9997447'],
 '10004844': ['9997447'],
 '100048460': ['1336344'],
 '100048461': ['1336344'],
 '10004853': ['9997447'],
 '10004929': ['9997447'],
 '10004934': ['9997447'],
 '10004941': ['9997447'],
 '10004950': ['9997447'],
 '10005062': ['9997447'],
 '10005068': ['9997447'],
 '10005076': ['9997447'],
 '100051070': ['1335616'],
 '10005122': ['9997447'],
 '100051996': ['1350608'],
 '100052321': ['95250273'],
 '100054161': ['1333639'],
 '10005426': ['1340161'],
 '10005441': ['1340515'],
 '10005572': ['1333777'],
 '10005729': ['1339546'],
 '100057660': ['100051996'],
 '100057805': ['1338342'],
 '100058485': ['1347418'],
 '10006078': ['10005572'],
 '10006104': ['10005572'],
 '10006110': ['10005572'],
 '10006116': ['10005572'],
 '10006145': ['10005572'],
 '10006154': ['10005572'],
 '10006166': ['10005572'],
 '10006178': ['10005572'],
 '10006189': ['10005572'],
 '10006203': ['10005572'],
 '10006214': ['10005572'],
 '10006227': ['10005572'],
 '10006235': ['10005572'],
 '10006249': ['10005572'],
 '10006257': ['10005572'],
 '10006270': ['10005572'],
 '100063684': ['1325680'],
 '100063685': ['1325680'],
 '100065422': ['1343214'],
 '100065612': ['1337431'],
 '100065614': ['1329089'],
 '100065616': ['1335220'],
 '100065618': ['1332945'],
 '10006563': ['1339546'],
 '100065707': ['1335520'],
 '10006616': ['1340515'],
 '10006673': ['1346517'],
 '100066770': ['1331795'],
 '100066772': ['1332945'],
 '100066773': ['1331795'],
 '10006678': ['1338804'],
 '100066892': ['1340825'],
 '100067026': ['1334068'],
 '10006733': ['10005572'],
 '100067923': ['1332378'],
 '100067984': ['1335025'],
 '100068284': ['1335433'],
 '100068338': ['1339070'],
 '10006872': ['1339546'],
 '100068804': ['1333910'],
 '100069048': ['1331780'],
 '100069170': ['1340896'],
 '100069181': ['1335456'],
 '100069193': ['1333910'],
 '100069311': ['1343393'],
 '10006943': ['1338804'],
 '100069641': ['1338768'],
 '10006977': ['10005572'],
 '100069829': ['1336946'],
 '100069843': ['1336946'],
 '100069941': ['6676318'],
 '100069942': ['6676318'],
 '100069943': ['6676318'],
 '100069944': ['6676318'],
 '100069945': ['6676318'],
 '100069946': ['6676318'],
 '100069947': ['6676318'],
 '100069948': ['6676318'],
 '100069949': ['6676318'],
 '100069950': ['6676318'],
 '100069951': ['6676318'],
 '100069952': ['6676318'],
 '100069953': ['6676318'],
 '100069954': ['6676318'],
 '100069955': ['6676318'],
 '100069956': ['6676318'],
 '100069957': ['6676318'],
 '100069958': ['6676318'],
 '100069959': ['6676318'],
 '100069960': ['6676318'],
 '100069961': ['6676318'],
 '100069962': ['6676318'],
 '100069963': ['6676318'],
 '100069964': ['6676318'],
 '100069965': ['6676318'],
 '100069966': ['6676318'],
 '100069967': ['6676318'],
 '100069968': ['6676318'],
 '100069969': ['6676318'],
 '100069970': ['6676318'],
 '100069971': ['6676318'],
 '100069972': ['6676318'],
 '100069973': ['6676318'],
 '100069974': ['6676318'],
 '100069975': ['6676318'],
 '100069976': ['6676318'],
 '100069977': ['6676318'],
 '100069978': ['6676318'],
 '100069979': ['6676318'],
 '100069980': ['6676318'],
 '100069981': ['6676318'],
 '100069982': ['6676318'],
 '100069983': ['6676318'],
 '100069984': ['6676318'],
 '100069985': ['6676318'],
 '100069986': ['6676318'],
 '100069987': ['6676318'],
 '100069988': ['6676318'],
 '100069989': ['6676318'],
 '100069990': ['6676318'],
 '100069991': ['6676318'],
 '100069992': ['6676318'],
 '100069993': ['6676318'],
 '100069994': ['6676318'],
 '100069995': ['6676318'],
 '100069996': ['6676318'],
 '10007264': ['10005572'],
 '10007359': ['10005572'],
 '100073986': ['1328601'],
 '100073987': ['1328601'],
 '10007407': ['1346517'],
 '100074887': ['1345529'],
 '100075009': ['1349172'],
 '100075010': ['1349172'],
 '10007542': ['10005572'],
 '10007556': ['10005572'],
 '10007563': ['10005572'],
 '100077116': ['1387008'],
 '100077148': ['1387008'],
 '10007765': ['1338804'],
 '10007856': ['1339546'],
 '10007966': ['10005572'],
 '10008006': ['1346517'],
 '10008019': ['10005572'],
 '100080675': ['1340853'],
 '100080677': ['1329688'],
 '100080688': ['1328366'],
 '100080692': ['1335675'],
 '100080700': ['1330981'],
 '100080704': ['1332242'],
 '100080720': ['1333130'],
 '10008075': ['10005572'],
 '10008092': ['1346517'],
 '10008164': ['10005572'],
 '10008170': ['10005572'],
 '100081713': ['1349084'],
 '10008177': ['10005572'],
 '10008183': ['10005572'],
 '10008186': ['10005572'],
 '10008193': ['10005572'],
 '10008198': ['10005572'],
 '100082196': ['100075009'],
 '100082216': ['100075010'],
 '100083251': ['1337687'],
 '10008339': ['1346517'],
 '100083391': ['1334263'],
 '100083694': ['1347800'],
 '100083712': ['1347800'],
 '100083744': ['1347800'],
 '100083773': ['1347800'],
 '100083809': ['1347800'],
 '100083833': ['1347800'],
 '100083843': ['1347800'],
 '100083853': ['1347800'],
 '10008474': ['10005572'],
 '10008499': ['10005572'],
 '10008506': ['10005572'],
 '10008510': ['10005572'],
 '10008515': ['10005572'],
 '10008522': ['10005572'],
 '10008529': ['10005572'],
 '10008540': ['10005572'],
 '100085781': ['1330064'],
 '100085919': ['1330064'],
 '100086194': ['1349652'],
 '100086222': ['1349652'],
 '100086316': ['1339257'],
 '100086336': ['1339257'],
 '100086357': ['1345562'],
 '100086627': ['1328193'],
 '100086651': ['1328193'],
 '100086842': ['1337462'],
 '100086853': ['1337462'],
 '10008827': ['10005572'],
 '10008849': ['10005572'],
 '10008855': ['10005572'],
 '10008862': ['10005572'],
 '10008907': ['1346517'],
 '100089128': ['1345910'],
 '100089572': ['1342526'],
 '100090001': ['1329427'],
 '100090072': ['1329427'],
 '100090098': ['1342526'],
 '10009024': ['10005572'],
 '10009034': ['10005572'],
 '10009044': ['10005572'],
 '100090510': ['1334247'],
 '10009151': ['10005572'],
 '100091980': ['1336564'],
 '100091995': ['1336564'],
 '100092015': ['1336564'],
 '100092357': ['1336564'],
 '100093006': ['1336564'],
 '100093035': ['1336564'],
 '100093040': ['1336564'],
 '100093044': ['1336564'],
 '100093052': ['1336564'],
 '100093062': ['1336564'],
 '100093070': ['1336564'],
 '100093073': ['1336564'],
 '10009326': ['1346517'],
 '100093495': ['1336564'],
 '100093498': ['1336564'],
 '100093501': ['1336564'],
 '100093743': ['1336564'],
 '100093748': ['1336564'],
 '100093753': ['1333047'],
 '100093761': ['1327460'],
 '100093762': ['1327460'],
 '100093765': ['1334999'],
 '100093767': ['1334999'],
 '100094344': ['1339764'],
 '10009454': ['10005572'],
 '10009787': ['1345568'],
 '100099597': ['1338286'],
 '100099605': ['1339384'],
 '100099813': ['1339305'],
 '100099815': ['1339305'],
 '10010353': ['1346517'],
 '100103953': ['1334300'],
 '100103959': ['1331590'],
 '100104068': ['1339522'],
 '100104075': ['1333115'],
 '100104078': ['1333386'],
 '100104112': ['1333386'],
 '100104114': ['1333386'],
 '100104115': ['1333386'],
 '10010532': ['10005572'],
 '100105818': ['1368168'],
 '100105885': ['1338850'],
 '100106123': ['1344093'],
 '100106126': ['1338850'],
 '100106160': ['1349652'],
 '100106303': ['1342040'],
 '10010843': ['1346517'],
 '10010847': ['10005572'],
 '10010968': ['10005572'],
 '10010992': ['10005572'],
 '10011001': ['10005572'],
 '10011011': ['10005572'],
 '10011017': ['10005572'],
 '10011140': ['10005572'],
 '100112163': ['1326508'],
 '100112192': ['1348075'],
 '100112213': ['100063685'],
 '100112236': ['100063685'],
 '100112446': ['1334789'],
 '100113278': ['1348986'],
 '10011649': ['10005572'],
 '100120240': ['42124675'],
 '100120241': ['42124675'],
 '100120242': ['42124675'],
 '100120243': ['42124675'],
 '100120244': ['42124675'],
 '100120245': ['42124675'],
 '100120246': ['42124675'],
 '100120247': ['42124675'],
 '100120248': ['42124675'],
 '100120249': ['42124675'],
 '100120250': ['42124675'],
 '100120251': ['42124675'],
 '100120252': ['42124675'],
 '100120253': ['42124675'],
 '100120254': ['42124675'],
 '100120255': ['42124675'],
 '100120256': ['42124675'],
 '100120257': ['42124675'],
 '100120258': ['42124675'],
 '100120259': ['42124675'],
 '100120260': ['42124675'],
 '100120261': ['42124675'],
 '100120262': ['42124675'],
 '100120263': ['42124675'],
 '100120264': ['42124675'],
 '100120265': ['42124675'],
 '100120266': ['42124675'],
 '100120267': ['42124675'],
 '100120268': ['42124675'],
 '100120269': ['42124675'],
 '100120270': ['42124675'],
 '100120271': ['42124675'],
 '100120272': ['42124675'],
 '100120273': ['42124675'],
 '100120274': ['42124675'],
 '100120275': ['42124675'],
 '100120276': ['42124675'],
 '100120277': ['42124675'],
 '100120278': ['42124675'],
 '100120279': ['42124675'],
 '100120280': ['42124675'],
 '100120281': ['42124675'],
 '100120282': ['42124675'],
 '100120283': ['42124675'],
 '100120284': ['42124675'],
 '100120285': ['42124675'],
 '100120286': ['42124675'],
 '100120287': ['42124675'],
 '100120288': ['42124675'],
 '100120289': ['42124675'],
 '100120290': ['42124675'],
 '100120291': ['42124675'],
 '100120292': ['42124675'],
 '100120293': ['42124675'],
 '100120294': ['42124675'],
 '100120295': ['42124675'],
 '100120296': ['42124675'],
 '100120297': ['42124675'],
 '100120298': ['42124675'],
 '100120299': ['42124675'],
 '100120300': ['42124675'],
 '100120301': ['42124675'],
 '100120302': ['42124675'],
 '100120303': ['42124675'],
 '100120304': ['42124675'],
 '100120305': ['42124675'],
 '100120306': ['42124675'],
 '100120307': ['42124675'],
 '100120308': ['42124675'],
 '100120309': ['42124675'],
 '100120310': ['42124675'],
 '100120311': ['42124675'],
 '100120312': ['42124675'],
 '100120313': ['42124675'],
 '100120314': ['42124675'],
 '100120315': ['42124675'],
 '100120316': ['42124675'],
 '100120317': ['42124675'],
 '100120318': ['42124675'],
 '100120319': ['42124675'],
 '100120320': ['42124675'],
 '100120321': ['42124675'],
 '100120322': ['42124675'],
 '100120323': ['42124675'],
 '100120324': ['42124675'],
 '100120325': ['42124675'],
 '100120326': ['42124675'],
 '100120327': ['42124675'],
 '100120328': ['42124675'],
 '100120329': ['42124675'],
 '100120330': ['42124675'],
 '100120331': ['42124675'],
 '100120332': ['42124675'],
 '100120333': ['42124675'],
 '100120334': ['42124675'],
 '100120335': ['42124675'],
 '100120336': ['42124675'],
 '100120337': ['42124675'],
 '100120338': ['42124675'],
 '100120339': ['42124675'],
 '100120340': ['42124675'],
 '100120341': ['42124675'],
 '100120342': ['42124675'],
 '100120343': ['42124675'],
 '100120344': ['42124675'],
 '100120345': ['42124675'],
 '100120346': ['42124675'],
 '100120347': ['42124675'],
 '100120348': ['42124675'],
 '100120349': ['42124675'],
 '100120350': ['42124675'],
 '100120351': ['42124675'],
 '100120352': ['42124675'],
 '100120353': ['42124675'],
 '100120354': ['42124675'],
 '100120355': ['42124675'],
 '100120356': ['42124675'],
 '100120357': ['42124675'],
 '100120358': ['42124675'],
 '100120359': ['42124675'],
 '100120360': ['42124675'],
 '100120361': ['42124675'],
 '100120362': ['42124675'],
 '100120363': ['42124675'],
 '100120364': ['42124675'],
 '100120365': ['42124675'],
 '100120366': ['42124675'],
 '100120367': ['42124675'],
 '100120368': ['42124675'],
 '100120369': ['42124675'],
 '100120370': ['42124675'],
 '100120371': ['42124675'],
 '100120372': ['42124675'],
 '100120373': ['42124675'],
 '100120374': ['42124675'],
 '100120375': ['42124675'],
 '100120376': ['42124675'],
 '100120377': ['42124675'],
 '100120378': ['42124675'],
 '100120379': ['42124675'],
 '100120380': ['42124675'],
 '100120381': ['42124675'],
 '100120382': ['42124675'],
 '100120383': ['42124675'],
 '100120384': ['42124675'],
 '100120385': ['42124675'],
 '100120386': ['42124675'],
 '100120387': ['42124675'],
 '100120388': ['42124675'],
 '100120389': ['42124675'],
 '100120390': ['42124675'],
 '100120391': ['42124675'],
 '100120392': ['42124675'],
 '100120393': ['42124675'],
 '100120394': ['42124675'],
 '100120395': ['42124675'],
 '100120396': ['42124675'],
 '100120397': ['42124675'],
 '100120398': ['42124675'],
 '100120399': ['42124675'],
 '100120400': ['42124675'],
 '100120401': ['42124675'],
 '100120402': ['42124675'],
 '100120403': ['42124675'],
 '100120404': ['42124675'],
 '100120405': ['42124675'],
 '100120406': ['42124675'],
 '100120407': ['42124675'],
 '100120408': ['42124675'],
 '100120409': ['42124675'],
 '100120410': ['42124675'],
 '100120411': ['42124675'],
 '100120412': ['42124675'],
 '100120413': ['42124675'],
 '100120414': ['42124675'],
 '100120415': ['42124675'],
 '100120416': ['42124675'],
 '100120417': ['42124675'],
 '100120418': ['42124675'],
 '100120419': ['42124675'],
 '100120420': ['42124675'],
 '100120421': ['42124675'],
 '100120422': ['42124675'],
 '100120423': ['42124675'],
 '100120424': ['42124675'],
 '100120425': ['42124675'],
 '100120426': ['42124675'],
 '100120427': ['42124675'],
 '100120428': ['42124675'],
 '100120429': ['42124675'],
 '100120430': ['42124675'],
 '100120431': ['42124675'],
 '100120432': ['42124675'],
 '100120433': ['42124675'],
 '100120434': ['42124675'],
 '100120435': ['42124675'],
 '100120436': ['42124675'],
 '100120437': ['42124675'],
 '100120438': ['42124675'],
 '100120439': ['42124675'],
 '100120440': ['42124675'],
 '100120441': ['42124675'],
 '100120442': ['42124675'],
 '100120443': ['42124675'],
 '100120444': ['42124675'],
 '100120445': ['42124675'],
 '100120446': ['42124675'],
 '100120447': ['42124675'],
 '100120448': ['42124675'],
 '100120449': ['42124675'],
 '100120450': ['42124675'],
 '100120451': ['42124675'],
 '100120452': ['42124675'],
 '100120453': ['42124675'],
 '100120454': ['42124675'],
 '100120455': ['42124675'],
 '100120456': ['42124675'],
 '100120457': ['42124675'],
 '100120458': ['42124675'],
 '100120459': ['42124675'],
 '100120460': ['42124675'],
 '100120461': ['42124675'],
 '100120462': ['42124675'],
 '100120463': ['42124675'],
 '100120464': ['42124675'],
 '100120465': ['42124675'],
 '100120466': ['42124675'],
 '100120467': ['42124675'],
 '100120468': ['42124675'],
 '100120874': ['1364592'],
 '100120877': ['1337903'],
 '100120978': ['1332423'],
 '100120982': ['1332423'],
 '100120988': ['100112163'],
 '100121159': ['100112163'],
 '100121160': ['100112163'],
 '100121161': ['100112163'],
 '100121162': ['100112163'],
 '100121163': ['100112163'],
 '100121164': ['100112163'],
 '100121165': ['100112163'],
 '100121166': ['100112163'],
 '100121167': ['100112163'],
 '100121168': ['100112163'],
 '100121169': ['100112163'],
 '100121170': ['100112163'],
 '100121171': ['100112163'],
 '100121172': ['100112163'],
 '100121173': ['100112163'],
 '100121174': ['100112163'],
 '100121175': ['100112163'],
 '100121176': ['100112163'],
 '100121177': ['100112163'],
 '100121178': ['100112163'],
 '100121179': ['100112163'],
 '100121180': ['100112163'],
 '100121181': ['100112163'],
 '100121182': ['100112163'],
 '100121183': ['100112163'],
 '100121184': ['100112163'],
 '100121185': ['100112163'],
 '100121186': ['100112163'],
 '100121187': ['100112163'],
 '100121188': ['100112163'],
 '100121189': ['100112163'],
 '100121190': ['100112163'],
 '100121191': ['100112163'],
 '100121192': ['100112163'],
 '100121193': ['100112163'],
 '100121194': ['100112163'],
 '100121195': ['100112163'],
 '100121196': ['100112163'],
 '100121197': ['100112163'],
 '100121198': ['100112163'],
 '100121199': ['100112163'],
 '100121200': ['100112163'],
 '100121201': ['100112163'],
 '100121202': ['100112163'],
 '100121203': ['100112163'],
 '100121204': ['100112163'],
 '100121205': ['100112163'],
 '100121206': ['100112163'],
 '100121207': ['100112163'],
 '100121208': ['100112163'],
 '100121209': ['100112163'],
 '100121210': ['100112163'],
 '100121211': ['100112163'],
 '100121212': ['100112163'],
 '100121213': ['100112163'],
 '100121214': ['100112163'],

In [44]:
df.groupby(['OBJECTID']).count().sort_values('ID', ascending=False)

,ID,OBJECTGUID,CHANGEID,NAME,TYPENAME,LEVEL,OPERTYPEID,PREVID,NEXTID,UPDATEDATE,STARTDATE,ENDDATE,ISACTUAL,ISACTIVE
OBJECTID,,,,,,,,,,,,,,
1327149,5,5,5,5,5,5,5,5,4,5,5,5,5,5
1329928,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1347185,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1326160,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1335012,4,4,4,4,4,4,4,4,3,4,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1336832,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1336833,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1336835,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1336836,1,1,1,1,1,1,1,1,1,1,1,1,1,1
99988719,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [54]:
df[df['OBJECTID'] == '1327149']

,ID,OBJECTID,OBJECTGUID,CHANGEID,NAME,TYPENAME,LEVEL,OPERTYPEID,PREVID,NEXTID,UPDATEDATE,STARTDATE,ENDDATE,ISACTUAL,ISACTIVE
11427,1639367,1327149,bce69d17-e2b9-4f74-926c-e82b1159bf4d,3634514,Вишневый Сад,снт,6,20,1639345,1639369,2015-11-10,1900-01-01,2015-11-02,0,0
11428,1639345,1327149,bce69d17-e2b9-4f74-926c-e82b1159bf4d,3634467,Вишневый Сад,дп,6,1,0,1639367,2017-11-16,1900-01-01,1900-01-01,0,0
11429,1639369,1327149,bce69d17-e2b9-4f74-926c-e82b1159bf4d,3634528,Вишневый Сад,снт,15,20,1639367,1639371,2017-12-10,2015-11-02,2016-09-29,0,0
11430,1639371,1327149,bce69d17-e2b9-4f74-926c-e82b1159bf4d,3634534,Вишневый Сад,снт,7,50,1639369,1828481,2020-02-14,2016-09-29,2020-02-14,0,0
11431,1828481,1327149,bce69d17-e2b9-4f74-926c-e82b1159bf4d,139243578,Вишневый сад,тер. СНТ,7,20,1639371,NaN,2020-02-14,2020-02-14,2079-06-06,1,1

# Classes

In [ ]:
from shapely import Point, LineString, LinearRing, Polygon, MultiLineString, MultiPoint, MultiPolygon


class Geoobject:
    ru_class_name = "Геообъект"

    def __init__(
            self,
            object: Point | LineString | LinearRing | Polygon | MultiLineString | MultiPoint | MultiPolygon):

        self.geom_type = object.geom_type
        self.coords = object.coords
        self.object = object


class BaseObject:
    """Базовый объект, использующийся для определения общих методов"""
    ru_class_name = "Базовый объект"

    def __init__(
            self,
            id: int,
            name: str,
            geo: Geoobject):
        self.id = id
        self.name = name
        self.geo = geo


class District(BaseObject):
    ru_class_name = "Район"

    def __init__(
            self,
            id: int,
            name: str,
            geo: Geoobject,
            parent_id: int,
            childs: list):
        super().__init__(id, name, geo)
        self.parent_id = parent_id
        self.childs = childs


class Street(BaseObject):
    ru_class_name = "Улица"

    def __init__(
            self,
            id: int,
            name: str,
            geo: Geoobject,
            parent_id: int,
            childs: list):
        super().__init__(id, name, geo)
        self.parent_id = parent_id
        self.childs = childs


class House(BaseObject):
    ru_class_name = "Дом"

    def __init__(
            self,
            id: int,
            name: str,
            geo: Geoobject,
            parent_id: int,
            number,
            zip,
            full_address,
            year: int,
            architector: str,
            style: str,
            **kwargs):
        super().__init__(id, name, geo)
        self.parent_id = parent_id
        self.number = number
        self.zip = zip
        self.full_address = full_address
        # culture
        self.year = year
        self.architector = architector
        self.style = style
        for kwarg_name, kwarg_value in kwargs:
            self.__setattr__(kwarg_name, kwarg_value)
        self.data = self.__dict__

# Other

In [2]:
obj = Object('102814491')

In [4]:
bod.coll('reestrobjects').find_one({'LEVELID': '8'})

{'_id': ObjectId('629fd4fbfdc3a4e7a42b587a'),
 'OBJECTID': '102814491',
 'OBJECTGUID': '8e22d916-f268-46a7-9b27-61e8738f898c',
 'CHANGEID': '224188794',
 'ISACTIVE': '1',
 'LEVELID': '8',
 'CREATEDATE': '2021-10-29',
 'UPDATEDATE': '2021-10-29'}

In [17]:
parent = obj.build_tree()['parents'][2]
parent.get_full_address()

'обл. Ульяновская, р-н. Цильнинский, тер.. автодорога Цивильск-Ульяновск'

In [18]:
pd.DataFrame(obj.get_params())

,ObjectID,Object Level Name,Param Type,Param Value,Param Type Description
0,1325381,Субъект РФ,ИФНС ФЛ,7300,ИФНС ФЛ
1,1325381,Субъект РФ,ИФНС ЮЛ,7300,ИФНС ЮЛ
2,1325381,Субъект РФ,ОКАТО,73000000000,ОКАТО
3,1325381,Субъект РФ,Код КЛАДР,7300000000000,Код адресного объекта одной строкой с признако...
4,1325381,Субъект РФ,Код КЛАДР без признака актуальности,73000000000,Код адресного объекта одной строкой без призна...
5,1325381,Субъект РФ,Реестровый номер,730000000000000000001,Реестровый номер адресного объекта
6,1325381,Субъект РФ,Признак присвоения адреса,0,"Признак в каком делении присвоен адрес, муници..."
7,1325381,Субъект РФ,OKTMO,73000000,OKTMO
8,1325381,Субъект РФ,Официальное наименование,Ульяновская область,Официальное наименование объекта(Региона)
9,1343033,Административный район,ИФНС ФЛ,7321,ИФНС ФЛ
10,1343033,Административный район,ОКАТО,73254000000,ОКАТО
11,1343033,Административный район,Код КЛАДР,7302000000000,Код адресного объекта одной строкой с признако...
12,1343033,Административный район,Код КЛАДР без признака актуальности,73020000000,Код адресного объекта одной строкой без призна...
13,1343033,Административный район,Реестровый номер,730000000000000000001,Реестровый номер адресного объекта
14,1343033,Административный район,Признак присвоения адреса,0,"Признак в каком делении присвоен адрес, муници..."
15,1343033,Административный район,ИФНС ФЛ,7300,ИФНС ФЛ
16,1343033,Административный район,ИФНС ЮЛ,7300,ИФНС ЮЛ
17,1343033,Административный район,ИНН ФЛ ТЕР УЧ,7321,Территориальный участок ИФНС ЮЛ
18,1343033,Административный район,ИФНС ЮЛ ТЕР УЧ,7321,Территориальный участок ИФНС ФЛ
19,102793407,Элемент планировочной структуры,OKTMO,73654415,OKTMO
20,102793407,Элемент планировочной структуры,Код КЛАДР,73020000000001100,Код адресного объекта одной строкой с признако...
21,102793407,Элемент планировочной структуры,Порядковый номер,5,Порядковый номер обьекта в рамках родителя
22,102793407,Элемент планировочной структуры,ОКАТО,73254815000,ОКАТО
23,102793407,Элемент планировочной структуры,Реестровый номер,736544150000005000002,Реестровый номер адресного объекта
24,102793407,Элемент планировочной структуры,Реестровый номер,736544150000005000011,Реестровый номер адресного объекта
25,102814491,Элемент улично-дорожной сети,OKTMO,73654415,OKTMO
26,102814491,Элемент улично-дорожной сети,ОКАТО,73254815000,ОКАТО
27,102814491,Элемент улично-дорожной сети,Код КЛАДР,73020000000001200,Код адресного объекта одной строкой с признако...
28,102814491,Элемент улично-дорожной сети,Порядковый номер,1,Порядковый номер обьекта в рамках родителя
29,102814491,Элемент улично-дорожной сети,Реестровый номер,736544150000005000101,Реестровый номер адресного объекта

In [12]:
doc = Document('admhierarchy', '102814491')

# Cuttin' the tree

In [146]:
data_colls = [
    'addrobj',
    'addrobjdivision',
    'addrobjparams',
    'admhierarchy',
    'apartments',
    'apartmentsparams',
    'carplaces',
    'carplacesparams',
    'changehistory',
    'houses',
    'housesparams',
    'munhierarchy', # broken
    'reestrobjects', # broken
    'rooms', # broken
    'roomsparams', # broken
    'steads', # broken
    'steadsparams', # broken
]

full_copy_colls = [
    # 'AS_NORMATIVE_DOCS',
    'normativedocs',
]

types_colls = [
    'addhousetypes',
    'addrobjtypes',
    'apartmenttypes',
    'housetypes',
    'normativedocskinds',
    'normativedocstypes',
    'objectlevels',
    'operationtypes',
    'paramtypes',
    'roomtypes'
]

In [151]:
dgrad_objects = utils.find_dgrad_objects() + ['1325381', '95250260']

def convert(coll_name: str):

    if coll_name in data_colls:
        source = pd.DataFrame(utils.cut_tree(coll_name, dgrad_objects, 'return'))
    elif (coll_name in full_copy_colls or coll_name in types_colls):
        source = pd.DataFrame(bod.coll(coll_name).find({}))

    schema = {}
    schema_nan = {}
    for key, value in utils.get_coll_schema(coll_name).items():
        if key in source.columns:
            schema.update({key: value['type']})
            schema_nan.update({key: value['none']})

    data = source.fillna(value=schema_nan, inplace=False).astype(
        schema).to_dict(orient='records')

    try:
        coll = bod_v2.coll(coll_name)
    except:
        coll = bod_v2.db.create_collection(coll_name)
    coll.delete_many({})
    if len(data) > 10000:
        i = 0
        j = len(data)
        chunk = 10000
        while i < j:
            coll.insert_many(data[i:i+chunk])
            i += chunk
    elif len(data) == 0:
        pass
    else:
        coll.insert_many(data)

for coll in bod.ls_colls:
    print(f'{coll} is in process')
    try: convert(coll)
    except: print('error')

addrobj is in process
carplacesparams is in process
error
objectlevels is in process
paramtypes is in process
normativedocs is in process
error
apartmentsparams is in process
addhousetypes is in process
apartmenttypes is in process
steads is in process
roomsparams is in process
error
addrobjtypes is in process
operationtypes is in process
housetypes is in process
addrobjdivision is in process
error
apartments is in process
changehistory is in process
carplaces is in process
error
AS_NORMATIVE_DOCS is in process
error
housesparams is in process
normativedocskinds is in process
rooms is in process
error
roomtypes is in process
steadsparams is in process
reestrobjects is in process
addrobjparams is in process
houses is in process
normativedocstypes is in process
munhierarchy is in process
admhierarchy is in process